/**
 * DB abstraction layer.
 * Supports SQLite (via better-sqlite3) and PostgreSQL (via pg).
 * Set DB_CLIENT=postgres in .env to use Postgres; default is sqlite.
 *
 * Interface:
 *   queryOne(text, params)   -> single row or null
 *   queryMany(text, params)  -> array of rows
 *   execute(text, params)    -> { lastInsertId } (insert/update/delete)
 */

import 'dotenv/config';
import Database from 'better-sqlite3';
import pg from 'pg';
import path from 'path';
import { fileURLToPath } from 'url';
import { mkdirSync } from 'fs';

const IS_POSTGRES = process.env.DB_CLIENT === 'postgres';

// ─── Postgres ────────────────────────────────────────────────────────────────

let pgPool = null;

function getPool() {
  if (!pgPool) {
    pgPool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  }
  return pgPool;
}

// Convert ? placeholders to $1, $2, ... for Postgres
function toPgParams(text) {
  let i = 0;
  return text.replace(/\?/g, () => `$${++i}`);
}

async function pgQueryOne(text, params = []) {
  const { rows } = await getPool().query(toPgParams(text), params);
  return rows[0] ?? null;
}

async function pgQueryMany(text, params = []) {
  const { rows } = await getPool().query(toPgParams(text), params);
  return rows;
}

async function pgExecute(text, params = []) {
  // For INSERT ... RETURNING id we extract lastInsertId automatically
  const returningText = /RETURNING\s+/i.test(text) ? text : text;
  const { rows } = await getPool().query(toPgParams(returningText), params);
  return { lastInsertId: rows[0]?.id ?? null, row: rows[0] ?? null };
}

// ─── SQLite ───────────────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, '../../data');
const DB_PATH = path.join(DATA_DIR, 'fabu.db');

let sqliteDb = null;

function getSqlite() {
  if (!sqliteDb) {
    mkdirSync(DATA_DIR, { recursive: true });
    sqliteDb = new Database(DB_PATH);
    sqliteDb.pragma('journal_mode = WAL');
    sqliteDb.pragma('foreign_keys = ON');
  }
  return sqliteDb;
}

async function sqliteQueryOne(text, params = []) {
  return getSqlite().prepare(text).get(...params) ?? null;
}

async function sqliteQueryMany(text, params = []) {
  return getSqlite().prepare(text).all(...params);
}

async function sqliteExecute(text, params = []) {
  const hasReturning = /RETURNING\s+/i.test(text);
  if (hasReturning) {
    const row = getSqlite().prepare(text).get(...params) ?? null;
    return { lastInsertId: row?.id ?? null, row };
  }
  const result = getSqlite().prepare(text).run(...params);
  return { lastInsertId: result.lastInsertRowid, row: null };
}

// ─── Schema init ─────────────────────────────────────────────────────────────

const SQLITE_SCHEMA = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS vehicles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    license_plate TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL DEFAULT 'PKW',
    description TEXT DEFAULT '',
    price_per_km REAL NOT NULL DEFAULT 0,
    flat_fee REAL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS reservations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    vehicle_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    date_to TEXT NOT NULL,
    time_from TEXT NOT NULL,
    time_to TEXT NOT NULL,
    reason TEXT NOT NULL,
    km_driven INTEGER,
    destination TEXT,
    status TEXT NOT NULL DEFAULT 'reserved',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
  );
`;

const PG_SCHEMA = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS vehicles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    license_plate TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL DEFAULT 'PKW',
    description TEXT DEFAULT '',
    price_per_km DOUBLE PRECISION NOT NULL DEFAULT 0,
    flat_fee DOUBLE PRECISION,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS reservations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    vehicle_id INTEGER NOT NULL REFERENCES vehicles(id),
    date DATE NOT NULL,
    date_to DATE NOT NULL,
    time_from TIME NOT NULL,
    time_to TIME NOT NULL,
    reason TEXT NOT NULL,
    km_driven INTEGER,
    destination TEXT,
    status TEXT NOT NULL DEFAULT 'reserved',
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_res_vehicle_date ON reservations(vehicle_id, date);
  CREATE INDEX IF NOT EXISTS idx_res_user ON reservations(user_id);
`;

async function ensurePgMigrations() {
  await getPool().query('ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS price_per_km DOUBLE PRECISION NOT NULL DEFAULT 0');
  await getPool().query('ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS flat_fee DOUBLE PRECISION');
  await getPool().query('ALTER TABLE reservations ADD COLUMN IF NOT EXISTS date_to DATE');
  await getPool().query('UPDATE reservations SET date_to = date WHERE date_to IS NULL');
}

function ensureSqliteMigrations() {
  const vehicleColumns = getSqlite().prepare("PRAGMA table_info(vehicles)").all();
  const hasPricePerKm = vehicleColumns.some((col) => col.name === 'price_per_km');
  const hasFlatFee = vehicleColumns.some((col) => col.name === 'flat_fee');
  if (!hasPricePerKm) {
    getSqlite().exec('ALTER TABLE vehicles ADD COLUMN price_per_km REAL NOT NULL DEFAULT 0');
  }
  if (!hasFlatFee) {
    getSqlite().exec('ALTER TABLE vehicles ADD COLUMN flat_fee REAL');
  }

  const columns = getSqlite().prepare("PRAGMA table_info(reservations)").all();
  const hasDateTo = columns.some((col) => col.name === 'date_to');
  if (!hasDateTo) {
    getSqlite().exec('ALTER TABLE reservations ADD COLUMN date_to TEXT');
    getSqlite().exec('UPDATE reservations SET date_to = date WHERE date_to IS NULL');
  } else {
    getSqlite().exec('UPDATE reservations SET date_to = date WHERE date_to IS NULL');
  }
}

export async function initDb() {
  if (IS_POSTGRES) {
    await getPool().query(PG_SCHEMA);
    await ensurePgMigrations();
    console.log('🐘 PostgreSQL verbunden und Schema bereit.');
  } else {
    getSqlite().exec(SQLITE_SCHEMA);
    ensureSqliteMigrations();
    console.log('🗄️  SQLite verbunden und Schema bereit.');
  }
}

// ─── Public exports ───────────────────────────────────────────────────────────

export const db = {
  queryOne: IS_POSTGRES ? pgQueryOne : sqliteQueryOne,
  queryMany: IS_POSTGRES ? pgQueryMany : sqliteQueryMany,
  execute: IS_POSTGRES ? pgExecute : sqliteExecute,
};
